FROM nginx:1.21.6

COPY default.conf /etc/nginx/conf.d/default.conf

COPY nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]

