name: yamlTest

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build Docker Image
      run: |
        docker build -t myimages/patients .
        docker build -f Dockerfile.nginx -t myimages/nginx .

    - name: Run Container
      run: |
        docker rm -f mycontainer
        docker rm -f mynginx
        docker run -td --name mycontainer --network app -p 0.0.0.0:4000:4000 myimages/patients
        docker run -td --name mynginx --network app -p 0.0.0.0:443:443 myimages/nginx
